[2024-12-14T11:34:10.495+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-14T11:34:10.524+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_instruction_fact_data.get_raw_data.extract_raw_instruction_fact manual__2024-12-14T11:34:07.397830+00:00 [queued]>
[2024-12-14T11:34:10.535+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_instruction_fact_data.get_raw_data.extract_raw_instruction_fact manual__2024-12-14T11:34:07.397830+00:00 [queued]>
[2024-12-14T11:34:10.535+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-14T11:34:10.551+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_raw_data.extract_raw_instruction_fact> on 2024-12-14 11:34:07.397830+00:00
[2024-12-14T11:34:10.560+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=878) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-14T11:34:10.563+0000] {standard_task_runner.py:63} INFO - Started process 883 to run task
[2024-12-14T11:34:10.563+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_instruction_fact_data', 'get_raw_data.extract_raw_instruction_fact', 'manual__2024-12-14T11:34:07.397830+00:00', '--job-id', '168', '--raw', '--subdir', 'DAGS_FOLDER/elt_instruction_fact.py', '--cfg-path', '/tmp/tmp2nl9p53t']
[2024-12-14T11:34:10.567+0000] {standard_task_runner.py:91} INFO - Job 168: Subtask get_raw_data.extract_raw_instruction_fact
[2024-12-14T11:34:10.660+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_instruction_fact_data.get_raw_data.extract_raw_instruction_fact manual__2024-12-14T11:34:07.397830+00:00 [running]> on host 472b63b715e1
[2024-12-14T11:34:10.795+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_instruction_fact_data' AIRFLOW_CTX_TASK_ID='get_raw_data.extract_raw_instruction_fact' AIRFLOW_CTX_EXECUTION_DATE='2024-12-14T11:34:07.397830+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-14T11:34:07.397830+00:00'
[2024-12-14T11:34:10.798+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-14T11:34:11.530+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-14T11:34:11.531+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/fit_task.py", line 49, in extract_raw
    for col_schema in table['schema']:
                      ~~~~~^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-12-14T11:34:11.551+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_instruction_fact_data, task_id=get_raw_data.extract_raw_instruction_fact, run_id=manual__2024-12-14T11:34:07.397830+00:00, execution_date=20241214T113407, start_date=20241214T113410, end_date=20241214T113411
[2024-12-14T11:34:11.575+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 168 for task get_raw_data.extract_raw_instruction_fact (string indices must be integers, not 'str'; 883)
[2024-12-14T11:34:11.590+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-14T11:34:11.630+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-14T11:34:11.636+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
