[2024-12-19T04:28:52.390+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-19T04:28:53.951+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT_enrollment_fact_data.wait_for_etl_instruction_fact_data manual__2024-12-19T04:28:26.256841+00:00 [queued]>
[2024-12-19T04:28:56.101+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT_enrollment_fact_data.wait_for_etl_instruction_fact_data manual__2024-12-19T04:28:26.256841+00:00 [queued]>
[2024-12-19T04:28:58.099+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-19T04:28:58.696+0000] {taskinstance.py:2330} INFO - Executing <Task(ExternalTaskSensor): wait_for_etl_instruction_fact_data> on 2024-12-19 04:28:26.256841+00:00
[2024-12-19T04:28:58.770+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=8563) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-19T04:28:58.778+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ELT_enrollment_fact_data', 'wait_for_etl_instruction_fact_data', 'manual__2024-12-19T04:28:26.256841+00:00', '--job-id', '1234', '--raw', '--subdir', 'DAGS_FOLDER/elt_enrollment_fact.py', '--cfg-path', '/tmp/tmpsthtyw2l']
[2024-12-19T04:29:00.726+0000] {standard_task_runner.py:91} INFO - Job 1234: Subtask wait_for_etl_instruction_fact_data
[2024-12-19T04:29:00.729+0000] {standard_task_runner.py:63} INFO - Started process 8592 to run task
[2024-12-19T04:29:02.699+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT_enrollment_fact_data.wait_for_etl_instruction_fact_data manual__2024-12-19T04:28:26.256841+00:00 [running]> on host 33a17f71e955
[2024-12-19T04:29:05.166+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ELT_enrollment_fact_data' AIRFLOW_CTX_TASK_ID='wait_for_etl_instruction_fact_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-19T04:28:26.256841+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-19T04:28:26.256841+00:00'
[2024-12-19T04:29:05.173+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-19T04:29:05.174+0000] {baseoperator.py:399} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2024-12-19T04:29:05.174+0000] {external_task.py:274} INFO - Poking for DAG 'etl_instruction_fact_data' on 2024-12-19T04:28:26.256841+00:00 ... 
[2024-12-19T04:29:05.216+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/session.py:79: DeprecationWarning: This method is deprecated and will be removed in future.
  return func(*args, session=session, **kwargs)

[2024-12-19T04:30:05.348+0000] {external_task.py:274} INFO - Poking for DAG 'etl_instruction_fact_data' on 2024-12-19T04:28:26.256841+00:00 ... 
[2024-12-19T04:31:05.385+0000] {external_task.py:274} INFO - Poking for DAG 'etl_instruction_fact_data' on 2024-12-19T04:28:26.256841+00:00 ... 
[2024-12-19T04:32:05.425+0000] {external_task.py:274} INFO - Poking for DAG 'etl_instruction_fact_data' on 2024-12-19T04:28:26.256841+00:00 ... 
[2024-12-19T04:33:05.465+0000] {external_task.py:274} INFO - Poking for DAG 'etl_instruction_fact_data' on 2024-12-19T04:28:26.256841+00:00 ... 
[2024-12-19T04:34:05.498+0000] {external_task.py:274} INFO - Poking for DAG 'etl_instruction_fact_data' on 2024-12-19T04:28:26.256841+00:00 ... 
[2024-12-19T04:35:05.587+0000] {external_task.py:274} INFO - Poking for DAG 'etl_instruction_fact_data' on 2024-12-19T04:28:26.256841+00:00 ... 
[2024-12-19T04:36:05.600+0000] {external_task.py:274} INFO - Poking for DAG 'etl_instruction_fact_data' on 2024-12-19T04:28:26.256841+00:00 ... 
[2024-12-19T04:37:05.613+0000] {external_task.py:274} INFO - Poking for DAG 'etl_instruction_fact_data' on 2024-12-19T04:28:26.256841+00:00 ... 
[2024-12-19T04:38:05.630+0000] {external_task.py:274} INFO - Poking for DAG 'etl_instruction_fact_data' on 2024-12-19T04:28:26.256841+00:00 ... 
[2024-12-19T04:39:05.658+0000] {external_task.py:274} INFO - Poking for DAG 'etl_instruction_fact_data' on 2024-12-19T04:28:26.256841+00:00 ... 
[2024-12-19T04:39:05.723+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-19T04:39:05.724+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 281, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 600.5494335941039 seconds exceeds the specified timeout of 600.0.
[2024-12-19T04:39:05.781+0000] {taskinstance.py:1206} INFO - Immediate failure requested. Marking task as FAILED. dag_id=ELT_enrollment_fact_data, task_id=wait_for_etl_instruction_fact_data, run_id=manual__2024-12-19T04:28:26.256841+00:00, execution_date=20241219T042826, start_date=20241219T042855, end_date=20241219T043905
[2024-12-19T04:39:05.985+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1234 for task wait_for_etl_instruction_fact_data (Sensor has timed out; run duration of 600.5494335941039 seconds exceeds the specified timeout of 600.0.; 8592)
[2024-12-19T04:39:06.041+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-19T04:39:06.136+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-19T04:39:06.154+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
