[2024-12-14T11:12:45.183+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-14T11:12:45.565+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: migration_fit_schema.insert_data.insert_data_instruction_fact manual__2024-12-14T11:12:20.987198+00:00 [queued]>
[2024-12-14T11:12:45.582+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: migration_fit_schema.insert_data.insert_data_instruction_fact manual__2024-12-14T11:12:20.987198+00:00 [queued]>
[2024-12-14T11:12:45.582+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-14T11:12:45.606+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_data.insert_data_instruction_fact> on 2024-12-14 11:12:20.987198+00:00
[2024-12-14T11:12:45.626+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=151) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-14T11:12:45.630+0000] {standard_task_runner.py:63} INFO - Started process 153 to run task
[2024-12-14T11:12:45.639+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'migration_fit_schema', 'insert_data.insert_data_instruction_fact', 'manual__2024-12-14T11:12:20.987198+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/etl_migrate.py', '--cfg-path', '/tmp/tmp1wya21fq']
[2024-12-14T11:12:45.644+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask insert_data.insert_data_instruction_fact
[2024-12-14T11:12:45.800+0000] {task_command.py:426} INFO - Running <TaskInstance: migration_fit_schema.insert_data.insert_data_instruction_fact manual__2024-12-14T11:12:20.987198+00:00 [running]> on host 472b63b715e1
[2024-12-14T11:12:46.096+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='migration_fit_schema' AIRFLOW_CTX_TASK_ID='insert_data.insert_data_instruction_fact' AIRFLOW_CTX_EXECUTION_DATE='2024-12-14T11:12:20.987198+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-14T11:12:20.987198+00:00'
[2024-12-14T11:12:46.097+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-14T11:12:46.402+0000] {logging_mixin.py:188} INFO - Transaction failed for table instruction_fact: can't adapt type 'NAType'
[2024-12-14T11:12:46.402+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-14T11:12:46.403+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/etl_task.py", line 112, in insert_data
    raise e
  File "/opt/airflow/dags/tasks/etl_task.py", line 104, in insert_data
    execute_values(cursor, insert_query, data, template=f"({placeholders})", page_size=1000)
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.ProgrammingError: can't adapt type 'NAType'
[2024-12-14T11:12:46.416+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=migration_fit_schema, task_id=insert_data.insert_data_instruction_fact, run_id=manual__2024-12-14T11:12:20.987198+00:00, execution_date=20241214T111220, start_date=20241214T111245, end_date=20241214T111246
[2024-12-14T11:12:46.431+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 16 for task insert_data.insert_data_instruction_fact (can't adapt type 'NAType'; 153)
[2024-12-14T11:12:46.463+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-14T11:12:46.495+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-14T11:12:46.501+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
