[2024-12-16T14:34:17.609+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: migration_fit_data.load_staging.create_staging_score_detail manual__2024-12-16T14:32:53.829690+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
